## This rule redirects to an external API
  [[redirects]]
  from = "/api/*"
  to = ""https://pokemonappapi2.herokuapp.com/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "/*"
  to = "/"
  status = 200